// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3EH-Cjy3HunMkpXMEBc7xElxoCNa52mQ',
    appId: '1:933431944957:web:4fd9571909b618f53d8094',
    messagingSenderId: '933431944957',
    projectId: 'cash-registry-f323b',
    authDomain: 'cash-registry-f323b.firebaseapp.com',
    storageBucket: 'cash-registry-f323b.appspot.com',
    measurementId: 'G-2MND48ZW24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3d-qW2cUncr99iLts9t9VILAPTl6jS8k',
    appId: '1:933431944957:android:0f5227062f69db2c3d8094',
    messagingSenderId: '933431944957',
    projectId: 'cash-registry-f323b',
    storageBucket: 'cash-registry-f323b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXwpCvUoU1W0AewAl4H9Z1WcLsQN0Axh0',
    appId: '1:933431944957:ios:b99f223944b2b8913d8094',
    messagingSenderId: '933431944957',
    projectId: 'cash-registry-f323b',
    storageBucket: 'cash-registry-f323b.appspot.com',
    iosBundleId: 'com.example.cashRegistry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXwpCvUoU1W0AewAl4H9Z1WcLsQN0Axh0',
    appId: '1:933431944957:ios:b99f223944b2b8913d8094',
    messagingSenderId: '933431944957',
    projectId: 'cash-registry-f323b',
    storageBucket: 'cash-registry-f323b.appspot.com',
    iosBundleId: 'com.example.cashRegistry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3EH-Cjy3HunMkpXMEBc7xElxoCNa52mQ',
    appId: '1:933431944957:web:6c291ced32ee06713d8094',
    messagingSenderId: '933431944957',
    projectId: 'cash-registry-f323b',
    authDomain: 'cash-registry-f323b.firebaseapp.com',
    storageBucket: 'cash-registry-f323b.appspot.com',
    measurementId: 'G-Z9FM0J2P1D',
  );
}
